name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~IntegrationTests" --collect:"XPlat Code Coverage"
    - name: Run Integration Tests
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName~IntegrationTests" --collect:"XPlat Code Coverage"
    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - name: Enforce Code Coverage Threshold (80%)
      run: ~/.dotnet/tools/reportgenerator -reports:"**/TestResults/**/*.xml" -targetdir:"coveragereport" -reporttypes:HtmlSummary minimumCoverageThresholds:lineCoverage=80